export const FETCH_MEALS_BEGIN = 'FETCH_MEALS_BEGIN'
export const FETCH_MEALS_SUCCESS = 'FETCH_MEALS_SUCCESS'
export const FETCH_MEALS_FAILURE = 'FETCH_MEALS_FAILURE'
export const GET_SINGLE_MEAL = 'GET_SINGLE_MEAL'
